server:
  port: 29087

spring:
  application:
    name: app-core
  profiles:
    active: @profiles.active@
  cloud:
    nacos:
      server-addr: @nacos.server-addr@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        group: @nacos.discovery.group@
        namespace: @nacos.discovery.namespace@
        ephemeral: false # false 永久实例，true 临时实例
      config:
        group: @nacos.config.group@
        namespace: @nacos.config.namespace@
  config:
    import:
      - optional:nacos:astro-code-common.yaml
      - optional:nacos:${spring.application.name}.yaml

dubbo:
  registry:
    address: nacos://@nacos.server-addr@
    username: @nacos.username@
    password: @nacos.password@
    parameters:
      namespace: @nacos.discovery.group@

easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置在方法上使用注解翻译
  is-enable-global: true
  #启用平铺模式 手动翻译无效
  is-enable-tile: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: false
  #使用@RpcTrans来标记哪些类可以进行RPC翻译，默认为关闭，多团队协作推荐开启
  is-enable-custom-rpc: false
  # ruoyi相关的框架请开启
  is-enable-map-result: false
  # 反向翻译数据库类型 mysql
  db-type: mysql
  # Mybatis-plus 为 3.5.3.2版本以上的3.x 版本请设置为true
  mp-new: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:io/charlie/app/core/**/xml/*.xml